modLoader = "javafml"
loaderVersion = "[32,)"
license = "MIT"

[[mods]]
    modId = "cavedelight"
    version = "${file.jarVersion}"
    logoFile = "cavedelight.png"
    authors = "TheValiantSquidward, Crydigo, platypushasnohat"
    displayName = "Cave Delight"
    description = '''
    Farmers Delight addon for Alex's Caves.
    '''

[[dependencies.cavedelight]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,1.20.2)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.cavedelight]]
    modId = "forge"
    mandatory = true
    versionRange = "[47.1.3,)"
    ordering = "AFTER"
    side = "BOTH"